stages: [ merge ]

merge-job:
  only:
  - main
  - internal
  - redhat
  stage: merge
  # Use ubi for compliance.
  image: quay.io/app-sre/ubi8-ubi:latest
  # Our runners do not execute unttaged jobs (... alex suspects).
  tags: [ shared ]
  before_script:
  # Install git. Could be useful ʕ •ᴥ•ʔ.
  - dnf install -qy git
  # Since RH self signs internal services we need to tell git to use the rh cert when talking
  # to gitlab. Also tell git how this job is called.
  - git config --global user.email "merge@bert"
  - git config --global user.name "mergeboy"
  script:
  - GIT_SSL_CAINFO=redhat/ca.cert git fetch https://$GITLAB_CREDENTIALS@gitlab.cee.redhat.com/lp-sre/package-operator.git internal:internal redhat:redhat
  - git fetch https://github.com/package-operator/package-operator.git main:main
  - git checkout internal
  - git merge -Xtheirs main
  - git merge -Xtheirs redhat
  - GIT_SSL_CAINFO=redhat/ca.cert git push https://$GITLAB_CREDENTIALS@gitlab.cee.redhat.com/lp-sre/package-operator.git main internal